package utils

import (
	"fmt"
	"os"
	"path"

	"github.com/alexandreLITHAUD/gitctx/internal/paths"
	"github.com/alexandreLITHAUD/gitctx/internal/ui"
)

func DoesContextFileExists(name string) bool {
	contextFilePath := path.Join(paths.GetGitctxConfigFolderPath(), name)
	if _, err := os.Stat(contextFilePath); os.IsNotExist(err) {
		return false
	}
	return true
}

func CreateGitctxContextFromScratch(name string) error {
	contextFilePath := path.Join(paths.GetGitctxConfigFolderPath(), name)

	if DoesContextFileExists(name) {
		fmt.Printf("Context '%s' already exists. Would you like to override it ?.\n", name)
		confirmed, err := ui.PromptForConfirmation("Answer (y)es or (n)o :")
		if err != nil {
			return fmt.Errorf("error reading confirmation input: %w", err)
		}
		if !confirmed {
			fmt.Println("Skipping creation of context file.")
			return nil
		}
	}

	destFile, err := os.Create(contextFilePath)
	if err != nil {
		return err
	}
	defer destFile.Close()

	_, err = destFile.WriteString("# Context generated by gitctx\n")
	if err != nil {
		return err
	}

	return nil
}
